### ISSUE TITLE
Problem with UWolframAlpha.Data.UIElements.cs Unity 2019.2.6f1

### ISSUE THREAD

**Issue by ASoldo** [andrew-raphael-lukasik/UWolframAlpha#1]
Hi, I have found your post and source code for UWolframAlpha but when I put it in my project I have errors with UWolframAlpha.Data.UIElements.cs. Can you help?

Assets/UWolframAlpha/UWolframAlpha.Data.UIElements.cs(304,10): error CS1061: 'IStyle' does not contain a definition for 'borderTopColor' and no accessible extension method 'borderTopColor' accepting a first argument of type 'IStyle' could be found (are you missing a using directive or an assembly reference?)

Assets/UWolframAlpha/UWolframAlpha.Data.UIElements.cs(304,33): error CS1061: 'IStyle' does not contain a definition for 'borderBottomColor' and no accessible extension method 'borderBottomColor' accepting a first argument of type 'IStyle' could be found (are you missing a using directive or an assembly reference?)

Assets/UWolframAlpha/UWolframAlpha.Data.UIElements.cs(304,59): error CS1061: 'IStyle' does not contain a definition for 'borderLeftColor' and no accessible extension method 'borderLeftColor' accepting a first argument of type 'IStyle' could be found (are you missing a using directive or an assembly reference?)

Assets/UWolframAlpha/UWolframAlpha.Data.UIElements.cs(304,83): error CS1061: 'IStyle' does not contain a definition for 'borderRightColor' and no accessible extension method 'borderRightColor' accepting a first argument of type 'IStyle' could be found (are you missing a using directive or an assembly reference?)

Do you know how to fix it? Thank you!

**Comment by andrew-raphael-lukasik** [comment]
Thank you for reporting. This is because in [2019.2 there is single borderColor property](https://docs.unity3d.com/2019.2/Documentation/ScriptReference/UIElements.IStyle.html) and it got broken up into [4 separate border color properties in 2019.3](https://docs.unity3d.com/2019.3/Documentation/ScriptReference/UIElements.IStyle.html)

**Comment by andrew-raphael-lukasik** [comment]
You can get rid of that error by either updating your Unity to 2019.3
**OR**
replacing this one line:
`style.borderTopColor = style.borderBottomColor = style.borderLeftColor = style.borderRightColor = color;`
with:
`style.borderColor = color;`

**Comment by ASoldo** [comment]
Thank you very much, i Will update Unity :)
