### ISSUE TITLE
How to query at runtime (MonoBehaviour)?

### ISSUE THREAD

**Issue by ASoldo** [andrew-raphael-lukasik/UWolframAlpha#2]
Hi, is it possible to send queries from specific object in the scene (MonoBehaviour) so I can have text input and text component then I can show response there in the text field. Also how to deal with response, I see there is CSV si I assume you need to parse it and then read what you want from there.
Can you please if is possible provide some snippets for this for me to look at? That would be a great help. The editor works like a cham.

**Comment by andrew-raphael-lukasik** [comment]
Hi, sure. Just bare functionality test would look something like this:
```
using UnityEngine;
public class RuntimeTest : MonoBehaviour
{
    [SerializeField] UnityEngine.UI.InputField _input = null;
    [SerializeField] TMPro.TMP_Text _output = null;
    void Start ()
    {
        _input.onEndEdit.AddListener( Query );
    }
    async void Query ( string text )
    {
        var response = await UWolframAlpha.Query.JSON( text );
        _output.text = response;
    }
}
```
This will print just raw json response from wolfram servers and this is not something you would want to show to an average mortal. **But** it's important for developers to be able to understand what Wolfram response really looks like. And this will be helpful for both debugging and deciding on what to show and how, so it's a good first step

**Comment by andrew-raphael-lukasik** [comment]
Please take a look into new [Examples](https://github.com/andrew-raphael-lukasik/UWolframAlpha/tree/master/Examples) folder for a code sample how to display outputs runtime

**Comment by andrew-raphael-lukasik** [comment]
Here is a simple example of how you may want to display deserialized (ie.: in form of struct and not just one big string) results from UWolframAlpha.Query.Data query:
```
async void Query ( string text )
{
    // query:
    var response = await UWolframAlpha.Query.Data( text );

    // create output view:
    foreach( var pod in response.pod_array )
    {
        string label = pod.title;
        /* create some kind of ui entry with this label */

        foreach( var subpod in pod.subpod_array )
        {
            var image = await UWolframAlpha.Query.Internal.DownloadTextureGif( subpod.img.src );
            /* put this image into that entry */

            // NOTE: it's a good^2 idea to dispose this image object once it's no longer needed (memory leak otherwise ie.: it will stay there for app lifetime)

            var plainText = subpod.plaintext;
            /* put this text into that entry so user can copy outputs in text form */
        }
    }
}
```
(working sample code for this you can find in that Examples directory)

**Comment by andrew-raphael-lukasik** [comment]
FYI: Code samples look different than code so far because commit f6eda43c869950812860bf62d4973007660e2e62 renamed things a bit for clarity reasons (update/re-download your copy please)

**Comment by ASoldo** [comment]
I'm having this error when I paste your script: 
Error	CS0234	The type or namespace name 'Query' does not exist in the namespace 'UWolframAlpha' (are you missing an assembly reference?)	Assembly-CSharp	C:\Users\Unity_dev_02\Documents\New Unity Project\Assets\RuntimeTester.cs	16

Editor script works fine... what am I missing here? I will update new version

**Comment by andrew-raphael-lukasik** [comment]
> Error CS0234 The type or namespace name 'Query' does not exist in the namespace 'UWolframAlpha'

f6eda43c869950812860bf62d4973007660e2e62 fixes that :) please download latest version

**Comment by ASoldo** [comment]
Just did, it works now. Thank you!

**Comment by ASoldo** [comment]
Its a shame that Wolfram returns most number properties as a string for example "Croatia population -> "plaintext": "4.19 million people (world rank: 128th) (2017 estimate)"" and there is no number for that, there are Pod "large cities" that have numbers you can use "Zagreb - 792875 people". All I wanna do is create a query like "Croatia population" and get number "4.190 000" for example. Is this possible? Sorry for spamming here, if you have discord or any place where we can talk so I don't spam here, that would be great. Thanks for your assistance!

**Comment by ASoldo** [comment]
Also when i go to my wolfram notebook and type "CountryData["Croatia", "Population"]" i get this "Quantity[4189353, "People"]" but in notebook its "4 189 353 people"
![Screen Shot 2020-03-30 at 21 06 44](https://user-images.githubusercontent.com/1175537/77951609-9fe88f00-72ca-11ea-8c69-38065a6553b5.png).

**Comment by andrew-raphael-lukasik** [comment]
I don't know how to request that number formatted differently, not my expertise. You may want to ask that on their forums maybe.
But if you would still want to parse that long string you can try something like this:
```
string text = "4.19 million people (world rank: 128th) (2017 estimate)";
double result = -1;
{
	string[] words = text.Split(' ');
	string number = words[0];
	if( double.TryParse( number , out result ) )
	{
		string suffix = words[1];
		if( suffix=="million" ) result *= 1e6;
		else if( suffix=="billion" ) result *= 1e9;
		else Debug.LogError($"'{suffix}' suffix not implemented yet");
	}
	else Debug.LogError($"error parsing '{number}' for number");
}
```
